# Generated by Django 3.1.7 on 2021-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reverse_check',
            name='used',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
    ]
