# Generated by Django 3.1.7 on 2021-03-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0002_auto_20210314_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FloBrand',
            new_name='Flo_Brand',
        ),
    ]
