# Generated by Django 3.1.7 on 2021-03-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0003_auto_20210323_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flo_id',
            old_name='polo_id',
            new_name='flo_id',
        ),
    ]
